/**
 * Gallery images, generated by `bun run gallery` from the (gitignored)
 * originals in gallery-originals/: `./gallery/<name>.webp` is the full view,
 * `./gallery/thumbs/<name>.webp` the grid tile. Ordered by filename; a leading
 * number (`03-torus-dao`) sets the order and is not part of the id, so the
 * `?image=` URL survives reordering. Dimensions are read at build time
 * (`?size`, see vite-plugins/image-size.ts), so the masonry lays out before
 * any image loads. Files are content-hashed by Vite.
 *
 * Alt text defaults to the humanized id ("torus-dao" → "Torus dao"); set real
 * alt text and a caption below, keyed by id.
 */
import type { ImageSize } from "../../vite-plugins/image-size.ts";

export interface GalleryImage {
	id: string;
	/** Full view (lightbox). */
	src: string;
	/** Grid tile (≤ 1000px wide), also the lightbox's placeholder while `src` loads. */
	thumb: string;
	width: number;
	height: number;
	alt: string;
	caption?: string;
}

const details: Record<string, { alt?: string; caption?: string }> = {
	"torus-hypergraph": {
		alt: "Torus Portal hypergraph: agents and permissions as glowing nodes in 3D",
		caption: "Torus Portal",
	},
	"torus-dao": {
		alt: "Torus DAO landing: the Themis statue in the dark, with links to Proposals, DAO Dashboard and Whitelist Applications",
		caption: "Torus DAO",
	},
	"torus-permissions": {
		alt: "Torus permission editor: capability paths drawn as a graph of namespace nodes",
		caption: "Torus Portal",
	},
	"prediction-swarm": {
		alt: "Prediction Swarm landing: a dithered title over search and cards for prophets, tickers and the predictor feed",
		caption: "Prediction Swarm",
	},
	"hoc-landing": {
		alt: "Higher Order Company landing: “The parallel future of computation”, introducing the Bend language and the HVM runtime",
		caption: "Higher Order Company",
	},
	"futureme-journey": {
		alt: "FutureMe journey: numbered activities grouped into phases along a dotted path",
		caption: "FutureMe",
	},
	"futureme-profile": {
		alt: "FutureMe student profile with achievements, a podium of careers and a professional profile",
		caption: "FutureMe",
	},
	"determinate-landing": {
		alt: "Determinate Intelligence landing: “Intelligence that compiles”, “Most AI is stochastic by design”, and the approach: type theory, formal methods and declarative reasoning",
		caption: "Determinate Intelligence",
	},
	"enlaza-landing": {
		alt: "Enlaza landing: protection plans for businesses and for individuals and families",
		caption: "Enlaza",
	},
	"torus-logo": {
		alt: "The Torus logo: two white arcs back to back, joined by a bar, on black",
		caption: "Torus",
	},
	"torus-ascii": {
		alt: "A wireframe torus with ASCII numerals floating through its middle",
		caption: "Torus",
	},
	"prediction-swarm-foresight": {
		alt: "Prediction Swarm: “The fractal nature of foresight” over a particle cloud, above prediction statistics",
		caption: "Prediction Swarm",
	},
	"commune-landing": {
		alt: "Commune landing: “Welcome to the commune” over a green network, with cards for governance, updates and docs",
		caption: "Commune",
	},
	"commune-logo": {
		alt: "The Commune logo: a C built from isometric cubes, white on black",
		caption: "Commune",
	},
	"commune-home": {
		alt: "Commune home: network statistics beside a green particle vortex, with governance, docs and community links",
		caption: "Commune",
	},
	"oneresult-search": {
		alt: "OneResult: an AI search box with suggestions for AI, docs and projects",
		caption: "OneResult",
	},
	"determinate-hero": {
		alt: "Determinate Intelligence hero: the name in large type above a fractal image",
		caption: "Determinate Intelligence",
	},
	"determinate-logo": {
		alt: "The Determinate Intelligence logo: a half circle against a bar, white on black",
		caption: "Determinate Intelligence",
	},
	"determinate-aigm": {
		alt: "AIGM landing: “A world that can't be forgotten”, an RPG run by an AI game master that can't cheat or forget",
		caption: "Determinate Intelligence",
	},
	"aifred-delegate": {
		alt: "AIFred landing: “You delegate. AIFred does it. You get results.” beside floating task cards",
		caption: "AIFred",
	},
	"jello-party-landing": {
		alt: "Ultimate Jello Party landing: colorful game characters and the line “Uma desculpa nostálgica para se divertir com os amigos!”",
		caption: "Ultimate Jello Party",
	},
	"e-logo": {
		alt: "An {e} logo: a lowercase e with a bar through it, between curly braces",
	},
	"e-site-nav": {
		alt: "Navigation bar of the {e} site: Home, About, Tech Stack, Work and Blog, with LinkedIn, GitHub and a theme toggle",
	},
	"aifred-landing": {
		alt: "AIFred landing: “O AIFred faz a organização da sua agenda” above a phone showing a chat",
		caption: "AIFred",
	},
};

const urls = import.meta.glob<string>("./gallery/*.webp", {
	eager: true,
	query: "?url",
	import: "default",
});
const thumbs = import.meta.glob<string>("./gallery/thumbs/*.webp", {
	eager: true,
	query: "?url",
	import: "default",
});
const sizes = import.meta.glob<ImageSize>("./gallery/*.webp", {
	eager: true,
	query: "?size",
	import: "default",
});

const fileName = (path: string) => path.split("/").pop() ?? path;

/** "./gallery/03-torus-dao.webp" → "torus-dao" (keep in sync with scripts/gallery.ts). */
const toId = (path: string) =>
	fileName(path)
		.replace(/\.[^.]+$/, "")
		.replace(/^\d+-/, "");

const humanize = (id: string) => {
	const words = id.replace(/-+/g, " ").trim();
	return words.charAt(0).toUpperCase() + words.slice(1);
};

export const galleryImages: GalleryImage[] = Object.keys(urls)
	// Numeric-aware, so "9-x" sorts before "10-x" without zero-padding.
	.sort((a, b) => a.localeCompare(b, "en", { numeric: true }))
	.map((path) => {
		const id = toId(path);
		return {
			id,
			src: urls[path],
			thumb: thumbs[`./gallery/thumbs/${fileName(path)}`] ?? urls[path],
			...sizes[path],
			alt: details[id]?.alt ?? humanize(id),
			caption: details[id]?.caption,
		};
	});

export function getGalleryImage(id: string): GalleryImage | undefined {
	return galleryImages.find((image) => image.id === id);
}
